version: '3'

services:
  kafka-manager:
    container_name: kafka-manager
    image: sheepkiller/kafka-manager:latest
    ports:
      - ${EXPOSED_PORT}:9000
    # depends_on:
    #   - kafka2
    environment:
      APPLICATION_SECRET: ${APPLICATION_SECRET}
      ZK_HOSTS: ${ZK_HOSTS}
    restart: always
    deploy:
      resources:
        limits:
          memory: 800M
    networks:
      - shared_network

networks:
  shared_network: