version: '3'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - ${EXPOSED_PORT_HTTP}:7474
      - ${EXPOSED_PORT_BOLT}:7687
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data
    # network_mode: "host"
    networks:
      - shared_network
    # restart: always
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  neo4j-data:

networks:
  shared_network:
    external:
      name: shared_network