version: '3'

services:
  hunter:
    container_name: hunter
    image: hunter:latest
    ports:
      - ${EXPOSED_PORT}:8080
    # restart: always
    volumes:
      - data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1G
volumes:
  data: