version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - ${EXPOSED_PORT}:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # restart: always
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  rabbitmq_data: