version: '3'

services:
  solr:
    image: solr:8.3
    container_name: solr
    ports:
      - ${SOLR_EXPOSED_PORT}:8983
    # depends_on:
    #   - zookeeper
    environment:
      ZK_HOSTS: ${ZK_HOSTS}
      SOLR_JAVA_MEM: "-Xms2g -Xmx2g"
    # restart: always
    volumes:
      - solr_data:/var/solr/
    command: sh -c "solr start -c -f"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 800M
    networks:
      - shared_network

networks:
  shared_network:
    external:
      name: shared_network
    
volumes:
  solr_data: