version: "3"
services:
  nginx:
    container_name: nginx
    image: ${NGINX_IMAGE}
    volumes:
    - ./templates:/etc/nginx/site-available
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=dev.test.com
    - NGINX_PORT=80
    restart: always
    networks:
      - shared_network
    deploy:
        resources:
          limits:
            memory: ${MEMORY}

networks:
  shared_network:
    external:
      name: shared_network