version: '3'

services:
  vault:
    container_name: vault
    network_mode: "host"
    image: vault:latest
    volumes:
        - ./vault/config:/vault/config
        - ./vault/policies:/vault/policies
        - ./vault/data:/vault/data
    # volumes:
    #     - vault_config:/vault/config
    #     - vault_policies:/vault/policies
    #     - vault_data:/vault/data
    ports:
        - 8200:8200
    environment:
        # - VAULT_DEV_LISTEN_ADDRESS=http://0.0.0.0:8200
        - VAULT_ADDR=http://0.0.0.0:8200
        - VAULT_API_ADDR=http://0.0.0.0:8200
        - VAULT_ADDRESS=http://0.0.0.0:8200
        # - VAULT_DEV_ROOT_TOKEN_ID="my-token"
    cap_add:
        - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
# volumes:
#   vault_config:
#   vault_policies:
#   vault_data: