version: '3.3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:1.24.0
    restart: always
    ports:
      - "${EXPOSED_PORT}:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  portainer_data:
