version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - "${EXPOSED_PORT}:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: