version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12.15-alpine
    # network_mode: "host"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - shared_network

volumes:
  pgdata:

networks:
  shared_network:
    external:
      name: shared_network